#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
  echo '❌ Prettier check failed: Run (npm run format), add changes and try to commit again.';
  false;
)
echo '✅ Prettier check passed.';


# Check ESLint Standards
# npm run check-lint ||
# (
#   echo '❌ ESLint check failed: Make the required changes listed above, add changes and try to commit again.'
#   false; 
# )
# echo '✅ ESLint check passed.';


# Check tsconfig standards
npm run check-types ||
(
  echo '❌ Type check failed: View the errors above.'
  false;
)
echo '✅ Type check passed.';


# Check build application
npm run check-build ||
(
  echo '❌ Build check failed: View the errors above.'
  false;
)
echo '✅ Build check passed.';


echo '✅ Your changes have been committed successfully.'
