#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Building and testing your project before pushing'

# Check build application
# if npm run check-build
# then
#   echo '✅ Build check passed';
# else
#   echo '❌ Build check failed: View the errors above'
#   false;
# fi

echo '✅ Your changes have been pushed successfully'