name: Axe check

on:
  pull_request:
    branches: [master]

jobs:
  axe-check:
    name: axe check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        run: npm ci

      - name: build application
        run: npm run build --if-present

      - name: start application
        run: npm run dev & npx wait-on http://localhost:3300

      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3300 --exit
