name: Build check

on:
  pull_request:
    branches: [master]

jobs:
  build-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: npm install
        run: npm ci

      - name: build application
        run: npm run build
