name: Unit tests

on:
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        run: npm ci

      - name: run unit tests
        run: npm run unit-test
